theme: jekyll-theme-midnight
title: "Fitness 4 Baddies"
description: "Are you a baddie? Welcome to the best thing that's ever happened to you."
gitorg: "https://github.com/alexac54767/Fitness_4_Baddies"
google_analytics:
